// <auto-generated />
using System;
using Airport_API.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Airport_API.Data.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Airport_API.Models.AirCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("id_city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("air_companies");
                });

            modelBuilder.Entity("Airport_API.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Airport_API.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirlineId")
                        .HasColumnType("integer")
                        .HasColumnName("id_airline");

                    b.Property<DateTime>("ArriveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrive_at");

                    b.Property<int?>("CityFromId")
                        .HasColumnType("integer")
                        .HasColumnName("id_city_from");

                    b.Property<int?>("CityToId")
                        .HasColumnType("integer")
                        .HasColumnName("id_city_to");

                    b.Property<DateTime>("DepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at");

                    b.Property<int>("PassengersCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("CityFromId");

                    b.HasIndex("CityToId");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("Airport_API.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FlightId")
                        .HasColumnType("integer")
                        .HasColumnName("id_flight");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<float?>("HandLuggageWeight")
                        .HasColumnType("real")
                        .HasColumnName("hand_luggage_weight");

                    b.Property<float?>("LuggageWeight")
                        .HasColumnType("real")
                        .HasColumnName("luggage_weight");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passport");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("Airport_API.Models.AirCompany", b =>
                {
                    b.HasOne("Airport_API.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Airport_API.Models.Flight", b =>
                {
                    b.HasOne("Airport_API.Models.AirCompany", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId");

                    b.HasOne("Airport_API.Models.City", "CityFrom")
                        .WithMany()
                        .HasForeignKey("CityFromId");

                    b.HasOne("Airport_API.Models.City", "CityTo")
                        .WithMany()
                        .HasForeignKey("CityToId");

                    b.Navigation("Airline");

                    b.Navigation("CityFrom");

                    b.Navigation("CityTo");
                });

            modelBuilder.Entity("Airport_API.Models.Passenger", b =>
                {
                    b.HasOne("Airport_API.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.Navigation("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
